apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: annotation-setting-material-menu
spec:
  targetRef:
    group: ""
    kind: MenuItem
  formSchema:
    - $formkit: "attachment"
      name: "icon"
      label: "图标"